config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'dashboard#home'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :admins

  get '/home', to: 'dashboard#home'

  # admins_controller
  get '/admin_list', to: 'admins#admin_list'
  get '/new_admin', to: 'admins#new_admin'
  post '/create_admin', to: 'admins#create_admin', as: 'create_admin'
  delete '/remove_admin/:id', to: 'admins#remove_admin', as: 'remove_admin'
  post '/reset_password/:id', to: 'admins#reset_password', as: 'reset_password'

  # invitations_controller
  get '/invite_admin', to: 'invitations#invite_admin'
  post '/send_admin_invitation', to: 'invitations#send_admin_invitation', as: 'send_admin_invitation'

  # movers_controller
  resources :movers, only: [:new]
  post 'upload_movers', to: 'movers#upload_file', as: 'upload_movers'

  # reports controller
  get 'movers_reports', to: 'reports#movers_reports', as: 'movers_reports'
  get '/csv_errors/:id', to: 'reports#csv_errors', as: 'csv_errors'
  get '/phantom_calendar/:id', to: 'reports#phantom_calendar', as: 'phantom_calendar'
  post 'cancel_movers_generator/:id', to: 'reports#cancel_movers_generator', as: 'cancel_movers_generator'
  get 'reports/:id/calendars', to: 'reports#calendars_index', as: 'calendars_index'
  get 'reports/:id/zip_calendars', to: 'reports#zip_calendars', as: 'zip_calendars'

  get '/calendars/*filepath' => 'calendars#show', as: 'calendar_show'
  namespace :calendar do
    # advertisers controller
    resources :advertisers do
      resources :advertiser_events
    end

    resources :category_filters, only: [:index, :update]

    resources :postal_code_covers, only: [:new, :create, :edit, :update, :destroy]

    # region configs controller
    resources :region_configs do
      collection do
        post :upload_pois
        post :upload_zones
      end

      resources :waste_disposal_zones, only: [:index] do
        resources :waste_pickups, only: [:index] do
          collection do
            post :save
            post :save_week_pattern
          end
        end
      end
    end
    post '/refresh_calendar/:id', to: 'region_configs#refresh_calendar', as: 'refresh_calendar'

    # month controller
    resources :months, only: [:edit, :update]
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def home
    reports = Report::Movers.includes(:calendars).completed_last(5).map{ |report| Report::MoversPresenter.new(report) }

    render 'dashboard/home', locals: {
      reports: reports,
      calendars: Report::MoversCalendar.group_by_day(:created_at, format: '%m/%d/%Y').count,
      available: ::Calendar::RegionConfig.with_wrong_status.empty?,
      calendars_weekly_current_month: Report::MoversCalendar.created_at_month(Time.zone.now).group_weekly,
      errors_weekly_current_month: Report::MoversError.created_at_month(Time.zone.now).group_weekly,
      calendars_monthly_overtime: Report::MoversCalendar.group_monthly,
      errors_monthly_overtime: Report::MoversError.group_monthly,
      parsed_count: Report::Movers.pluck(:parsed_count).sum,
      total_files: Report::Movers.count,
    }
  end

end

app/views/dashboard/home.html.haml
%h2.text-center
  %i Canada Post dashboard
.container
  .row
    .col-md-6
      .panel.panel-info
        .panel-heading
          %h3.panel-title.text-center Current month weekly stat
        .panel-body
          = line_chart [{name: 'Generated',data: calendars_weekly_current_month}, {name: 'Errors', data: errors_weekly_current_month}], download: "weekly_stat_from_#{Date::MONTHNAMES[Time.now.month].downcase}"
          %h6
            %b This month sumarize
            = "Generated: #{calendars_weekly_current_month.values.sum}"
            = "Errors: #{errors_weekly_current_month.values.sum}"
    .col-md-6
      .panel.panel-info
        .panel-heading
          %h3.panel-title.text-center Reports
        .panel-body
          .row
            .btn.btn-primary.btn-md.upload-file-expand-button
              Upload File
            .upload-file-expand-area
              .well
                - if available
                  .form-wrapper
                    =form_tag upload_movers_path, multipart: true do |f|
                      .form-group
                        = label_tag :file
                        = file_field_tag :file
                      .form-group
                        = label_tag :headless_chrome
                        = check_box_tag :headless_chrome
                      .form-group
                        = submit_tag 'Upload', class: 'btn btn-block btn-lg btn-primary'

                - else
                  %h2.text-center Some of Region Config is invalid. Repair it before uploading file.
          %hr
          .row
            %h4.text-center
              Last 5 completed reports
            %table.table.table-hover
              %thead
                %tr
                  %th Date
                  %th File name
                  %th Calendars
                  %th
              %tbody
                - reports.each do |report|
                  %tr
                    %td= report.date
                    %td= report.file_name
                    %td= report.calendars.count
                    %td
                      - if report.calendars.present?
                        = link_to calendars_index_path(report.id), class: 'btn btn-primary btn-sm' do
                          .glyphicon.glyphicon-list
  .row
    .col-md-6
      .panel.panel-info
        .panel-heading
          %h3.panel-title.text-center Monthly overtime stat
        .panel-body
          = line_chart [{name: 'Generated',data: calendars_monthly_overtime}, {name: 'Errors', data: errors_monthly_overtime}], download: 'monthly_overall_stat'
    .col-md-6
      .panel.panel-info
        .panel-heading
          %h3.panel-title.text-center Calendars Stat
        .panel-body
          = line_chart calendars, download: 'daily_generated_calendars'
  .row
    .col-md-6
      .panel.panel-info
        .panel-heading
          %h3.panel-title.text-center Overall
        .panel-body
          = pie_chart({'generated' => calendars_monthly_overtime.values.sum, 'errors' => errors_monthly_overtime.values.sum })
    .col-md-6
      .panel.panel-info
        .panel-heading
          %h3.panel-title.text-center Sumarize
        .panel-body.text-center
          %div= "Uploaded files: #{total_files}"
          %div= "Total calendars: #{calendars_monthly_overtime.values.sum}"
          %div= "Total errors: #{errors_monthly_overtime.values.sum}"
          %div= "Total people: #{parsed_count}"

:javascript
  upload_movers_file();