config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'dashboard#home'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :admins

  get '/home', to: 'dashboard#home'

  # admins_controller
  get '/admin_list', to: 'admins#admin_list'
  get '/new_admin', to: 'admins#new_admin'
  post '/create_admin', to: 'admins#create_admin', as: 'create_admin'
  delete '/remove_admin/:id', to: 'admins#remove_admin', as: 'remove_admin'
  post '/reset_password/:id', to: 'admins#reset_password', as: 'reset_password'

  # invitations_controller
  get '/invite_admin', to: 'invitations#invite_admin'
  post '/send_admin_invitation', to: 'invitations#send_admin_invitation', as: 'send_admin_invitation'

  # movers_controller
  resources :movers, only: [:new]
  post 'upload_movers', to: 'movers#upload_file', as: 'upload_movers'

  # reports controller
  get 'movers_reports', to: 'reports#movers_reports', as: 'movers_reports'
  get '/csv_errors/:id', to: 'reports#csv_errors', as: 'csv_errors'
  get '/phantom_calendar/:id', to: 'reports#phantom_calendar', as: 'phantom_calendar'
  post 'cancel_movers_generator/:id', to: 'reports#cancel_movers_generator', as: 'cancel_movers_generator'
  get 'reports/:id/calendars', to: 'reports#calendars_index', as: 'calendars_index'
  get 'reports/:id/zip_calendars', to: 'reports#zip_calendars', as: 'zip_calendars'

  get '/calendars/*filepath' => 'calendars#show', as: 'calendar_show'
  namespace :calendar do
    # advertisers controller
    resources :advertisers do
      resources :advertiser_events
    end

    resources :category_filters, only: [:index, :update]

    resources :postal_code_covers, only: [:new, :create, :edit, :update, :destroy]

    # region configs controller
    resources :region_configs do
      collection do
        post :upload_pois
        post :upload_zones
      end

      resources :waste_disposal_zones, only: [:index] do
        resources :waste_pickups, only: [:index] do
          collection do
            post :save
            post :save_week_pattern
          end
        end
      end
    end
    post '/refresh_calendar/:id', to: 'region_configs#refresh_calendar', as: 'refresh_calendar'

    # month controller
    resources :months, only: [:edit, :update]
  end

end

app/views/partials/_alert.haml
.alert-wrapper
  - if flash[:success] || flash[:notice]
    .alert.alert-success.alert-dismissible
      .container
        = flash[:success] || flash[:notice]
        %button.close{"data-dismiss" => "alert", :type => "button"}
          %span ×
  - elsif flash[:danger] || flash[:alert]
    .alert.alert-danger
      .container
        = flash[:danger] || flash[:alert]

app/views/partials/_navbar.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{'data-target': '#navbar-collapse-1', 'data-toggle': 'collapse', type: 'button'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Canada Post', current_admin ? root_path : new_admin_session_path, class: 'navbar-brand'
    #navbar-collapse-1.navbar-collapse.collapse
      -if current_admin
        %ul.nav.navbar-nav
          %li{class: "#{'active' if current_page? movers_reports_path}"}
            = link_to "Movers Reports", movers_reports_path
          %li{class: "#{'active' if current_page? calendar_advertisers_path}"}
            = link_to "Advertisers", calendar_advertisers_path
          %li{class: "#{'active' if current_page? calendar_region_configs_path}"}
            = link_to "Regions Configs", calendar_region_configs_path
          %li{class: "#{'active' if current_page? admin_list_path}"}
            = link_to "Manage admins", admin_list_path
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign out", destroy_admin_session_path, method: :delete