config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'dashboard#home'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :admins

  get '/home', to: 'dashboard#home'

  # admins_controller
  get '/admin_list', to: 'admins#admin_list'
  get '/new_admin', to: 'admins#new_admin'
  post '/create_admin', to: 'admins#create_admin', as: 'create_admin'
  delete '/remove_admin/:id', to: 'admins#remove_admin', as: 'remove_admin'
  post '/reset_password/:id', to: 'admins#reset_password', as: 'reset_password'

  # invitations_controller
  get '/invite_admin', to: 'invitations#invite_admin'
  post '/send_admin_invitation', to: 'invitations#send_admin_invitation', as: 'send_admin_invitation'

  # movers_controller
  resources :movers, only: [:new]
  post 'upload_movers', to: 'movers#upload_file', as: 'upload_movers'

  # reports controller
  get 'movers_reports', to: 'reports#movers_reports', as: 'movers_reports'
  get '/csv_errors/:id', to: 'reports#csv_errors', as: 'csv_errors'
  get '/phantom_calendar/:id', to: 'reports#phantom_calendar', as: 'phantom_calendar'
  post 'cancel_movers_generator/:id', to: 'reports#cancel_movers_generator', as: 'cancel_movers_generator'
  get 'reports/:id/calendars', to: 'reports#calendars_index', as: 'calendars_index'
  get 'reports/:id/zip_calendars', to: 'reports#zip_calendars', as: 'zip_calendars'

  get '/calendars/*filepath' => 'calendars#show', as: 'calendar_show'
  namespace :calendar do
    # advertisers controller
    resources :advertisers do
      resources :advertiser_events
    end

    resources :category_filters, only: [:index, :update]

    resources :postal_code_covers, only: [:new, :create, :edit, :update, :destroy]

    # region configs controller
    resources :region_configs do
      collection do
        post :upload_pois
        post :upload_zones
      end

      resources :waste_disposal_zones, only: [:index] do
        resources :waste_pickups, only: [:index] do
          collection do
            post :save
            post :save_week_pattern
          end
        end
      end
    end
    post '/refresh_calendar/:id', to: 'region_configs#refresh_calendar', as: 'refresh_calendar'

    # month controller
    resources :months, only: [:edit, :update]
  end

end

app/models/report/movers.rb
require 'csv'

class Report::Movers < ApplicationRecord
  self.table_name_prefix = 'report_'

  enum status: %w(pending in_progress completed canceling canceled zip_generating)

  has_many :calendars, class_name: Report::MoversCalendar, foreign_key: 'report_movers_id'
  has_many :wrong_records, class_name: Report::MoversError, foreign_key: 'report_movers_id', dependent: :destroy

  scope :created_at_desc, -> { order(created_at: :desc) }
  scope :not_finished, -> { where(status: not_finished_statuses)  }
  scope :canceled_with_calendars, -> { where(status: Report::Movers.statuses[:canceled]).joins(:calendars) }
  scope :between_date, -> (start_date, end_date) { where('created_at BETWEEN ? AND ?', start_date.to_date, end_date.to_date.end_of_day) }
  scope :completed_last, -> (number) { order(created_at: :desc).where(status: Report::Movers.statuses[:completed]).first(number) }

  def working?
    working_statuses = %w(pending in_progress)
    working_statuses.include?(status)
  end

  private

  def self.not_finished_statuses
    not_finished_statuses = %w(pending in_progress canceling)
    not_finished_statuses.map { |status| Report::Movers.statuses[status] }
  end
end

app/models/report/movers_calendar.rb
class Report::MoversCalendar < ApplicationRecord
  self.table_name_prefix = 'report_'

  belongs_to :report_movers, class_name: Report::Movers

  scope :created_at_month, -> (date) { where("created_at > ? AND created_at < ?", date.beginning_of_month, date.end_of_month) }
  scope :group_weekly, -> { group_by_week(:created_at, format: '%m/%d/%Y').count  }
  scope :group_monthly, -> { group_by_month(:created_at, format: '%m/%d/%Y').count  }
end

app/models/report/movers_error.rb
class Report::MoversError < ApplicationRecord
  self.table_name_prefix = 'report_'

  belongs_to :report_movers, class_name: Report::Movers

  enum error_type: %w(record_invalid location_invalid map_generation_error)

  scope :record_invalid, -> { where(error_type: Report::MoversError.error_types[:record_invalid]) }
  scope :locations, -> { where(error_type: Report::MoversError.error_types[:location_invalid]) }
  scope :map_generation, -> { where(error_type: Report::MoversError.error_types[:map_generation_error]) }
  scope :created_at_month, -> (date) { where("created_at > ? AND created_at < ?", date.beginning_of_month, date.end_of_month) }
  scope :group_weekly, -> { group_by_week(:created_at, format: '%m/%d/%Y').count  }
  scope :group_monthly, -> { group_by_month(:created_at, format: '%m/%d/%Y').count  }

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  skip_before_action :authenticate_admin!, only: [ :phantom_calendar ]

  def movers_reports
    start_date, end_date = Parser::WeekPickerService.new(params[:week]).call
    reports_presenter = Report::Movers.includes(:calendars).between_date(start_date, end_date).created_at_desc.map{ |report| Report::MoversPresenter.new(report) }
    render 'reports/movers_reports', locals: { movers_reports: reports_presenter, start_date: start_date, end_date: end_date }
  end

  def cancel_movers_generator
    Report::CancelGeneratorService.new(params[:id]).call
    redirect_to movers_reports_path
  rescue ActiveRecord::RecordNotFound
    redirect_to movers_reports_path, flash: { alert: t('flash.errors.report.not_found') }
  end

  def csv_errors
    respond_to do |format|
      format.csv { send_data Report::MoversToCsvService.new(params[:id]).call }
    end
  rescue => e
    redirect_to movers_reports_path, flash: { alert: t('flash.errors.report.not_found') }
  end

  def phantom_calendar
    @headless_chrome = params[:headless_chrome]
    calendar_data = Calendar::PhantomViewService.new(params[:id], phantom_calendar_params, params[:region_id]).call
    I18n.with_locale(set_locale(calendar_data[:mover])) do
      render 'calendar/show', layout: 'layouts/calendar', locals: calendar_data
    end
  end

  def calendars_index
    report = Report::Movers.find(params[:id])
    calendar_presenters = report.calendars.order(number: :asc)
    unless params[:skip_pagination]
      calendar_presenters = calendar_presenters.paginate(per_page: 50, page: params[:page])
    end
    render 'reports/calendars_index', locals: { report: report, calendars: calendar_presenters, skip_pagination: params[:skip_pagination] }
  rescue ActiveRecord::RecordNotFound
    redirect_to movers_reports_path, flash: { alert: t('flash.errors.report.not_found') }
  end

  def zip_calendars
    zip_collection = Report::MoversCalendar::ZipCollection.new(report_id: params[:id])

    if zip_collection.report.zip_path.present?
      send_file zip_collection.zip_path, disposition: :attachment
    else
      zip_collection.call
      redirect_to movers_reports_path, flash: { notice: t('flash.notice.reports.zip_is_being_generated') }
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to movers_reports_path, flash: { alert: t('flash.errors.report.not_found') }
  end

  private

  def set_locale(mover)
    mover.french? ? :fr : :en
  end

  def phantom_calendar_params
    params.permit(:first_name, :last_name, :address_line_1, :address_line_2, :city, :province, :postal_code, :lat, :long,
                  :kit_no, :record_id, :start_date, :language, :multi_unit_building, :bagbun, :dmc, :list_order, :waste_pickup_url)
  end
end

app/views/reports/_errors_modal.html.haml
.modal.fade{id: "#{modal_id}", role: 'dialog', tabindex: '-1'}
  .modal-dialog{:role => 'document'}
    .modal-content
      .modal-header
        %button.close{'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button'}
          %span{'aria-hidden': 'true'} ×
        %h4.modal-title Report errors
      .modal-body
        %table.table.table-hover
          %thead
            %tr
              %th Record Id
              %th Errors
          %tbody
            - errors.each do |error|
              %tr
                %td= error.row
                %td= error.message
      .modal-footer
        %button.btn.btn-default{'data-dismiss': 'modal', type: 'button'} Close

app/views/reports/calendars_index.html.haml
.container
  .row
    - if report.working? || report.zip_generating?
      .btn.btn-md.btn-primary.disabled
        Working . . .
    - else
      =link_to zip_calendars_path(report.id), class: 'btn btn-md btn-primary' do
        - if report.zip_path
          .glyphicon.glyphicon-plus
          Download Zip
        - else
          .glyphicon.glyphicon-plus
          Zip calendars
    - if skip_pagination
      = link_to 'Paginate', calendars_index_path(id: report.id, skip_pagination: nil), class: 'btn btn-md btn-primary'
    - else
      = link_to 'Show all', calendars_index_path(id: report.id, skip_pagination: true), class: 'btn btn-md btn-primary'
  .row.calendar-list
    - calendars.each do |calendar|
      %div
        = link_to "Calendar_#{calendar.path.split("/").last.split("-").first}", calendar.path, target: '_blank'
  - unless skip_pagination
    .row.pull-left
      %div= page_entries_info calendars
      %div= will_paginate calendars, renderer: BootstrapPagination::Rails

app/views/reports/movers_reports.html.haml
.container
  = form_tag movers_reports_path, method: :get do
    .week-picker-field
      = text_field_tag :week, "#{start_date}-#{end_date}", id: 'weekpicker', class: 'form-control'
    = submit_tag 'Week Filter', class: 'btn btn-primary btn-md'
  - if movers_reports.empty?
    %h2 No reports in this week
  - else
    %table.table.table-hover
      %thead
        %tr
          %th Date
          %th File name
          %th Total records
          %th Parsed records
          %th Records Invalid
          %th Location Invalid
          %th Map Generation Invalid
          %th Stauts
          %th Actions
      %tbody
        - movers_reports.each do |report|
          %tr
            %td= report.date
            %td= report.file_name
            %td= report.total_records
            %td= report.parsed_count
            %td
              = report.invalid_records.count
              - if report.invalid_records.count.between?(1, 100)
                %button.btn.btn-info.btn-xs{'data-target': "#invalid-records-#{report.id}", 'data-toggle': 'modal', type: 'button'}
                  Details
                = render 'reports/errors_modal', modal_id: "invalid-records-#{report.id}", errors: report.invalid_records
            %td
              = report.invalid_locations.count
              - if report.invalid_locations.count.between?(1, 100)
                %button.btn.btn-info.btn-xs{'data-target': "#invalid-locations-#{report.id}", 'data-toggle': 'modal', type: 'button'}
                  Details
                = render 'reports/errors_modal', modal_id: "invalid-locations-#{report.id}", errors: report.invalid_locations
            %td
              = report.map_generation.count
              - if report.map_generation.count.between?(1, 100)
                %button.btn.btn-info.btn-xs{'data-target': "#map_generation_error-#{report.id}", 'data-toggle': 'modal', type: 'button'}
                  Details
                = render 'reports/errors_modal', modal_id: "map_generation_error-#{report.id}", errors: report.map_generation
            %td= report.status.humanize
            %td
              - if report.working?
                = link_to cancel_movers_generator_path(report), method: :post, class: 'btn btn-danger btn-sm' do
                  Cancel
              = link_to csv_errors_path(report, format: :csv), class: 'btn btn-success btn-sm' do
                .glyphicon.glyphicon-download
                Csv
              - if report.calendars.present?
                = link_to calendars_index_path(report.id), class: 'btn btn-primary btn-sm' do
                  .glyphicon.glyphicon-list